PUBLIC_ROLE_LIKE = "Gamma"

FEATURE_FLAGS = {
    "AG_GRID_TABLE": True,
}
FEATURE_CHART_PLUGINS_EXPERIMENTAL=True
FEATURE_THEME_ENABLE_DARK_THEME_SWITCH=True
FEATURE_AG_GRID_TABLE_ENABLED=True
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = False
TALISMAN_ENABLED = False
